apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata: # kpt-merge: default/example-cluster-name
  name: nephio-workload-cluster
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: config.porch.kpt.dev|Repository|default|example-cluster-name
    nephio.org/cluster-name: nephio-workload-cluster
spec:
  content: Package
  deployment: true
  git:
    branch: main
    directory: /
    repo: http://172.18.0.200:3000/nephio/nephio-workload-cluster.git
    secretRef:
      name: nephio-workload-cluster-access-token-porch
  type: git
