apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata: # kpt-merge: default/example-cluster-name
  name: nephio-workload-cluster-repo
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: config.porch.kpt.dev|Repository|default|example-cluster-name
spec:
  content: Package
  deployment: true
  git:
    branch: main
    directory: /
    repo: http://172.18.0.200:3000/nephio/nephio-workload-cluster-repo.git
    secretRef:
      name: nephio-workload-cluster-repo-access-token-porch
  type: git
