apiVersion: infra.nephio.org/v1alpha1
kind: Token
metadata: # kpt-merge: default/example-site-name-access-token-porch
  name: nephio-workload-cluster-access-token-porch
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: infra.nephio.org|Token|default|example-site-name-access-token-porch
    nephio.org/cluster-name: nephio-workload-cluster
spec: {}
