apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-metallb
  name: nephio-workload-cluster-metallb
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-metallb'
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: metallb
    repo: catalog-distros-sandbox
    revision: v2.0.0
  downstream:
    package: nephio-workload-cluster-metallb
    repo: mgmt-staging
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: nephio-workload-cluster
