apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-vlanindex
  name: nephio-workload-cluster-vlanindex
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-vlanindex'
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: vlanindex
    repo: catalog-infra-capi
    revision: v2.0.0
  downstream:
    package: nephio-workload-cluster-vlanindex
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: nephio-workload-cluster
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: nephio-workload-cluster
